import connect from "../db/mongoDatabase.js";
import User from '../models/userModel.js';
import Plant from '../models/PLantModel.js';
class EditService{

    async editInformation(newData, user_id){

        try{

            await connect();
            
            const user = await User.findOne({_id: user_id.id});
            const data = JSON.parse(newData);

            for (const key in data) {
                const value = data[key];
                if(key == "email"){
                    user.email = value;
                }
                else if(key == "description"){
                    user.description = value;
                }
                else if(key == "profile_img"){
                    console.log("TODO");
                }
                else if(key == "cover_img"){
                    console.log("TODO");
                }
            }

            await user.save();

            console.log("Datele au fost schimbate");
            return user;

        } catch (error) {
            console.log(error);
        }

    }

    async addNameForPlants(){
        await connect();
        const plants = await Plant.find({});

        const plantNames = [
            'Arborvitae',
            'Begonia',
            'Caladium',
            'Dianthus',
            'Euonymus',
            'Fuchsia',
            'Geranium',
            'Hosta',
            'Impatiens',
            'Jasmine',
            'Kale',
            'Lily',
            'Marigold',
            'Nasturtium',
            'Orchid',
            'Petunia',
            'Quince',
            'Rose',
            'Snapdragon',
            'Tulip',
            'Violet',
            'Willow',
            'Xerophyte',
            'Yarrow',
            'Zinnia',
            'Aloe',
            'Bamboo',
            'Cactus',
            'Daffodil',
            'Eucalyptus',
            'Fern',
            'Gladiolus',
            'Hyacinth',
            'Iris',
            'Juniper',
            'Lavender',
            'Magnolia',
            'Narcissus',
            'Oleander',
            'Pansy',
            'Quince',
            'Rosemary',
            'Sunflower',
            'Tansy',
            'Umbrella Plant',
            'Vinca',
            'Wisteria',
            'Xanthosoma',
            'Yucca',
            'Zebra Grass',
            'Acanthus',
            'Bellflower',
            'Camellia',
            'Dandelion',
            'Echinacea',
            'Forget-Me-Not',
            'Gerbera',
            'Hibiscus',
            'Ivy',
            'Jonquil',
            'Kangaroo Paw',
            'Larkspur',
            'Morning Glory',
            'Nigella',
            'Oregano',
            'Peony',
            'Queen Anne\'s Lace',
            'Ranunculus',
            'Snowdrop',
            'Thyme',
            'Uva Ursi',
            'Verbena',
            'Water Lily',
            'Xerophyllum',
            'Yellow Archangel',
            'Zantedeschia',
            'Ageratum',
            'Baby\'s Breath',
            'Calendula',
            'Dill',
            'Everlasting',
            'Foxglove',
            'Gazania',
            'Heliotrope',
            'Impala Lily',
            'Jack-in-the-Pulpit',
            'Kaffir Lily',
            'Love-in-a-Mist',
            'Meadow Rue',
            'Nemesia',
            'Oxalis',
            'Paintbrush',
            'Quaking Grass',
            'Ribbon Grass',
            'Snow-in-Summer',
            'Tidy Tips',
            'Uvularia',
            'Valerian',
            'Windflower',
            'Xyris',
            'Yerba Buena',
            'Zebra Plant',
            'African Daisy',
            'Baby Blue Eyes',
            'Candytuft',
            'Delphinium',
            'Euphorbia',
            'Feather Grass',
            'Globe Amaranth',
            'Honesty',
            'Ice Plant',
            'Johnny Jump-Up',
            'Kangaroo Paw',
            'Lantana',
            'Moonflower',
            'Nicotiana',
            'Osteospermum',
            'Penstemon',
            'Queen\'s Cup',
            'Rudbeckia',
            'Statice',
            'Tickseed',
            'Umbrella Palm',
            'Veronica',
            'Wandering Jew',
            'Xerophyllum tenax',
            'Yellow-Eyed Grass',
            'Zinnia elegans',
            'Acanthus mollis',
            'Balloon Flower',
            'Canna Lily',
            'Dahlia',
            'Elephant Ear',
            'Foxtail Lily',
            'Gloriosa Lily',
            'Hollyhock',
            'Impatiens balsamina',
            'Japanese Anemone',
            'Knapweed',
            'Lamb\'s Ears',
            'Meadow Saffron',
            'Nigella damascena',
            'Oriental Poppy',
            'Pansy Orchid',
            'Queen Anne\'s Pocket Melons',
            'Rocket Larkspur',
            'Sun Rose',
            'Toad Lily',
            'Upright Knotweed',
            'Viola cornuta',
            'Wild Petunia',
            'Xerophyllum asphodeloides',
            'Yellow Archangel',
            'Zebra Plant',
            'Aloe vera',
            'Bamboo palm',
            'Calathea',
            'Dumbcane',
            'Elephant bush',
            'Fan palm',
            'Grape ivy',
            'Haworthia',
            'Ivy gourd',
            'Jade plant',
            'Kentia palm',
            'Lipstick plant',
            'Majesty palm',
            'Norfolk Island pine',
            'Orchid cactus',
            'Peace lily',
            'Queen\'s tears',
            'Rubber plant',
            'Snake plant',
            'Tradescantia',
            'Umbrella tree',
            'Venus flytrap',
            'Wandering Jew',
            'Xanthosoma sagittifolium',
            'Yucca elephantipes',
            'ZZ plant',
            'Zebra haworthia',
            'Ageratum houstonianum',
            'Bellis perennis',
            'Calendula officinalis',
            'Dianthus barbatus',
            'Eustoma grandiflorum',
            'Freesia alba',
            'Gazania rigens',
            'Helianthus annuus',
            'Impatiens balsamina',
            'Jasminum officinale',
            'Kniphofia uvaria',
            'Lathyrus odoratus',
            'Malva sylvestris',
            'Nemesia strumosa',
            'Osteospermum ecklonis',
            'Pelargonium hortorum',
            'Quisqualis indica',
            'Rosa \'Peace\'',
            'Salvia splendens',
            'Tagetes erecta',
            'Uvularia grandiflora',
            'Viola tricolor',
            'Wisteria sinensis',
            'Xerophyllum tenax',
            'Yucca filamentosa',
            'Zantedeschia aethiopica',
            'Achillea millefolium',
            'Bambusa ventricosa',
            'Caladium bicolor',
            'Datura metel',
            'Echium vulgare',
            'Fuchsia hybrida',
            'Gypsophila paniculata',
            'Heliotropium arborescens',
            'Impatiens walleriana',
            'Jatropha curcas',
            'Kniphofia praecox',
            'Lavandula angustifolia',
            'Musa paradisiaca',
            'Narcissus poeticus',
            'Ophiopogon japonicus',
            'Passiflora incarnata',
            'Quercus robur',
            'Rosa \'Double Delight\'',
            'Salvia officinalis',
            'Thunbergia alata',
            'Ulex europaeus',
            'Verbena bonariensis',
            'Wisteria floribunda',
            'Xylosma congestum',
            'Yucca gloriosa',
            'Zinnia elegans',
            'Acanthus hungaricus',
            'Bellis annua',
            'Calendula arvensis',
            'Dianthus deltoides',
            'Eustoma russellianum',
            'Fragaria vesca',
            'Geranium sanguineum',
            'Hemerocallis lilioasphodelus',
            'Inula helenium',
            'Jasminum humile',
            'Kniphofia ensifolia',
            'Lathyrus latifolius',
            'Malva moschata',
            'Nemophila maculata',
            'Oenothera biennis',
            'Paeonia lactiflora',
            'Quercus cerris',
            'Rosa \'Fragrant Cloud\'',
            'Salvia nemorosa',
            'Thuja occidentalis',
            'Ulmus glabra',
            'Verbena canadensis',
            'Wisteria frutescens',
            'Xyris caroliniana',
            'Yucca recurvifolia',
            'Zizia aurea',
            'Adiantum capillus-veneris',
            'Begonia semperflorens',
            'Callicarpa bodinieri',
            'Dictamnus albus',
            'Eranthis hyemalis',
            'Festuca glauca',
            'Gaura lindheimeri',
            'Hedera helix',
            'Impatiens hawkeri',
            'Juncus effusus',
            'Kniphofia rooperi',
            'Lamium maculatum',
            'Melampodium paludosum',
            'Nierembergia gracilis',
            'Ophiopogon planiscapus',
            'Papaver orientale',
            'Quercus ilex',
            'Rosa \'Garden Party\'',
            'Salvia coccinea',
            'Tradescantia zebrina',
            'Urtica dioica',
            'Verbena hastata',
            'Wisteria macrostachya',
            'Xerophyllum asphodeloides',
            'Yucca whipplei',
            'Zizania aquatica',
            'Abutilon hybridum',
            'Begonia tuberosa',
            'Callistephus chinensis',
            'Digitalis purpurea',
            'Erechtites hieraciifolius',
            'Festuca ovina',
            'Gentiana lutea',
            'Helleborus niger',
            'Impatiens glandulifera',
            'Juncus tenuis',
            'Kniphofia uvaria \'Nobilis\'',
            'Lantana camara',
            'Mentha piperita',
            'Nicotiana alata',
            'Ophiopogon planiscapus \'Nigrescens\''
          ];

        plants.forEach(async plant => {
            plant.name = plantNames[Math.floor(Math.random() * plants.length)];
            await plant.save();
        });
    }

}

export default new EditService();
